version: '3.8'

services:
  elif-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=10.10.1.1,192.168.13.215,127.0.0.1,orders.elif,sales.elif,admin.elif,api.elif
      - CORS_ALLOWED_ORIGINS=http://10.10.1.1:3000,http://10.10.1.1:3001,http://10.10.1.1:3002,http://192.168.13.215:3000,http://192.168.13.215:3001,http://192.168.13.215:3002,http://orders.elif,http://sales.elif,http://admin.elif,https://orders.elif,https://sales.elif,https://admin.elif
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/media:/app/media
      - ./backend:/app
    restart: unless-stopped
    networks:
      - elif-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  elif-network:
    external: true
