# Generated by Django 4.2.7 on 2025-09-21 18:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_add_unit_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
