# Generated by Django 4.2.7 on 2025-09-21 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20250921_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_received',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
