# Generated by Django 4.2.7 on 2025-09-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_deliveryitem_quantity_received_and_more'),
    ]

    operations = [
    ]
