# Generated by Django 4.2.7 on 2025-09-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_enable_manual_compatible_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sellable',
            field=models.BooleanField(default=True, help_text='Whether products in this category can be sold at POS'),
        ),
    ]
