# Generated by Django 4.2.7 on 2025-09-21 22:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_max_stock_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(help_text='Quantity in base unit', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit used for this movement (for display purposes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.unit'),
        ),
    ]
