# Generated by Django 4.2.7 on 2025-09-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_stockmovement_quantity_and_more'),
    ]

    operations = [
    ]
