# Generated by Django 4.2.7 on 2025-10-02 18:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_convert_to_base_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_packaging',
            field=models.BooleanField(default=False, help_text='Whether this product has packaging consignation'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packaging consignation price (e.g., bottle deposit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_section',
            field=models.CharField(blank=True, help_text='Storage section code (e.g., A12, G11, K10, C33)', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(choices=[('SSO', 'Back Storage'), ('STR', 'Front Storage')], default='STR', help_text='Storage type: SSO for back storage, STR for front storage', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('return', 'Stock Return'), ('adjustment', 'Stock Adjustment'), ('cost_update', 'Cost Price Update')], max_length=20),
        ),
    ]
