# Generated by Django 4.2.7 on 2025-10-23 05:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_has_packaging_product_packaging_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='standard_price_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Standard price 1 (required)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_price_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price 2 (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_price_3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price 3 (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_price_4',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price 4 (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_price_5',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price 5 (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productunit',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard price for this specific unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productunit',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price for this specific unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Standard retail price (legacy - use standard_price_1 instead)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
