# Generated by Django 4.2.7 on 2025-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('confirmed', 'Confirmed by Supplier'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
