# Generated by Django 4.2.7 on 2025-09-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_populate_units'),
        ('purchases', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit for this delivery item', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit for this order item', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
    ]
