# Generated by Django 4.2.7 on 2025-09-21 18:29

from django.db import migrations
from decimal import Decimal


def convert_purchase_quantities(apps, schema_editor):
    """Convert existing purchase quantities to decimal format using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        # Convert PurchaseOrderItem quantities
        cursor.execute("""
            UPDATE purchases_purchaseorderitem 
            SET quantity_ordered = CAST(quantity_ordered AS TEXT)
        """)
        
        # Convert DeliveryItem quantities
        cursor.execute("""
            UPDATE purchases_deliveryitem 
            SET quantity_received = CAST(quantity_received AS TEXT)
        """)


def reverse_convert_purchase_quantities(apps, schema_editor):
    """Reverse conversion - convert decimal back to integer using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        # Convert PurchaseOrderItem quantities back to integers
        cursor.execute("""
            UPDATE purchases_purchaseorderitem 
            SET quantity_ordered = CAST(quantity_ordered AS INTEGER)
        """)
        
        # Convert DeliveryItem quantities back to integers
        cursor.execute("""
            UPDATE purchases_deliveryitem 
            SET quantity_received = CAST(quantity_received AS INTEGER)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_deliveryitem_quantity_received_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_purchase_quantities, reverse_convert_purchase_quantities),
    ]
