# Generated by Django 4.2.7 on 2025-09-21 22:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_stockmovement_quantity_and_more'),
        ('purchases', '0006_alter_deliveryitem_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity_received',
            field=models.FloatField(default=0, help_text='Quantity received in base unit', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit for this delivery item (for display purposes)', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost per unit in the unit used', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.FloatField(help_text='Quantity ordered in base unit', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit for this order item (for display purposes)', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost per unit in the unit used', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
