# Generated by Django 4.2.7 on 2025-09-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_convert_to_base_units'),
        ('purchases', '0008_auto_20250921_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'product', 'unit')},
        ),
    ]
