# Generated by Django 4.2.7 on 2025-09-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_populate_units'),
        ('sales', '0003_saleitem_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product', 'unit')},
        ),
    ]
