# Generated by Django 4.2.7 on 2025-09-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_cost_update_movement_type'),
        ('sales', '0004_alter_saleitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('wholesale', 'Wholesale')], default='standard', help_text='Price mode used for this sale item', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product', 'unit', 'price_mode')},
        ),
    ]
