# Generated by Django 4.2.7 on 2025-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_price_mode_to_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost at time of sale (frozen for historical accuracy)', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit at time of sale (frozen for historical accuracy)', max_digits=10),
        ),
    ]
