# Generated by Django 4.2.7 on 2025-09-21 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20250921_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
