# Generated by Django 4.2.7 on 2025-09-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_saleitem_quantity_alter_saleitem_unit_and_more'),
    ]

    operations = [
    ]
