# Generated by Django 4.2.7 on 2025-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_sale_paid_amount_sale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for partial payments', null=True),
        ),
    ]
