# Generated by Django 4.2.7 on 2025-10-06 16:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0020_product_has_packaging_product_packaging_price_and_more'),
        ('sales', '0021_sale_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='packaging_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total packaging consignation amount', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalePackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity of packaging items', validators=[django.core.validators.MinValueValidator(0.001)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Packaging price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total packaging price', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('exchange', 'Exchange'), ('consignation', 'Consignation (Paid)'), ('due', 'Due (To be returned)')], default='consignation', help_text='Packaging status', max_length=20)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name for due packaging tracking', max_length=200)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone for due packaging tracking', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this packaging item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product that has packaging', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_items', to='sales.sale')),
                ('unit', models.ForeignKey(blank=True, help_text='Unit used for this packaging item', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('sale', 'product', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='PackagingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('return', 'Return for refund'), ('exchange', 'Exchange for new packaging')], default='return', max_length=20)),
                ('quantity_returned', models.FloatField(help_text='Quantity of packaging returned', validators=[django.core.validators.MinValueValidator(0.001)])),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded for returned packaging', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_returns', to=settings.AUTH_USER_MODEL)),
                ('sale_packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salepackaging')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
