# Generated by Django 4.2.7 on 2025-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
