# Generated by Django 4.2.7 on 2025-09-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_populate_units'),
        ('sales', '0002_sale_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit used for this sale item', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
    ]
