# Generated by Django 4.2.7 on 2025-09-21 11:10

from django.db import migrations
from decimal import Decimal


def fix_biscuits_malgaches_costs(apps, schema_editor):
    """Fix the cost prices for Biscuits Malgaches sale items (divide by 1000)"""
    SaleItem = apps.get_model('sales', 'SaleItem')
    Sale = apps.get_model('sales', 'Sale')
    
    # Find all sale items for Biscuits Malgaches
    biscuits_items = SaleItem.objects.filter(product__name='Biscuits Malgaches')
    
    print(f"Found {biscuits_items.count()} Biscuits Malgaches sale items to fix")
    
    for item in biscuits_items:
        # Divide the costs by 1000 to fix the currency error
        old_unit_cost = item.unit_cost
        old_total_cost = item.total_cost
        
        item.unit_cost = item.unit_cost / 1000
        item.total_cost = item.total_cost / 1000
        item.save()
        
        print(f"Fixed item {item.id}: {old_unit_cost} -> {item.unit_cost} (unit cost)")
        print(f"Fixed item {item.id}: {old_total_cost} -> {item.total_cost} (total cost)")
    
    # Update sale cost_amount to reflect the corrected costs
    for sale in Sale.objects.all():
        total_cost = sum(item.total_cost for item in sale.items.all())
        old_cost = sale.cost_amount
        sale.cost_amount = total_cost
        sale.save()
        print(f"Updated sale {sale.sale_number}: {old_cost} -> {total_cost}")


def reverse_fix_biscuits_malgaches_costs(apps, schema_editor):
    """Reverse the fix (multiply by 1000)"""
    SaleItem = apps.get_model('sales', 'SaleItem')
    Sale = apps.get_model('sales', 'Sale')
    
    # Find all sale items for Biscuits Malgaches
    biscuits_items = SaleItem.objects.filter(product__name='Biscuits Malgaches')
    
    for item in biscuits_items:
        item.unit_cost = item.unit_cost * 1000
        item.total_cost = item.total_cost * 1000
        item.save()
    
    # Update sale cost_amount
    for sale in Sale.objects.all():
        total_cost = sum(item.total_cost for item in sale.items.all())
        sale.cost_amount = total_cost
        sale.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20250921_1057'),
    ]

    operations = [
        migrations.RunPython(fix_biscuits_malgaches_costs, reverse_fix_biscuits_malgaches_costs),
    ]
