# Generated by Django 4.2.7 on 2025-09-21 18:28

from django.db import migrations
from decimal import Decimal


def convert_saleitem_quantities(apps, schema_editor):
    """Convert existing SaleItem quantities to decimal format using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE sales_saleitem 
            SET quantity = CAST(quantity AS TEXT)
        """)


def reverse_convert_saleitem_quantities(apps, schema_editor):
    """Reverse conversion - convert decimal back to integer using raw SQL"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE sales_saleitem 
            SET quantity = CAST(quantity AS INTEGER)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.RunPython(convert_saleitem_quantities, reverse_convert_saleitem_quantities),
    ]
