# Generated by Django 4.2.7 on 2025-09-21 22:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_stockmovement_quantity_and_more'),
        ('sales', '0014_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(help_text='Quantity in base unit', validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit used for this sale item (for display purposes)', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit in the unit used (frozen for historical accuracy)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in the unit used', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
