# Generated by Django 4.2.7 on 2025-09-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_return_returnitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='original_sale_item',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='return_order',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='sale',
            name='original_sale',
            field=models.ForeignKey(blank=True, help_text='Original sale for returns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('return', 'Return')], default='sale', help_text='Type of transaction: sale or return', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='original_sale_item',
            field=models.ForeignKey(blank=True, help_text='Original sale item for returns', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem'),
        ),
        migrations.DeleteModel(
            name='Return',
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
    ]
