# Generated by Django 4.2.7 on 2025-09-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_returnitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount to be paid', max_digits=10),
        ),
    ]
