version: '3.8'

services:
  elif-admin-app:
    build:
      context: ./beverage_management_system
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3002:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://192.168.237.215:8000
    volumes:
      - ./beverage_management_system/build:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - elif-network

networks:
  elif-network:
    external: true
