# Generated by Django 4.2.7 on 2025-09-21 18:27

from django.db import migrations
from decimal import Decimal


def convert_integer_to_decimal(apps, schema_editor):
    """Convert existing integer values to decimal format using raw SQL"""
    db_alias = schema_editor.connection.alias
    
    # Update Product quantities using raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE products_product 
            SET stock_quantity = CAST(stock_quantity AS TEXT),
                min_stock_level = CAST(min_stock_level AS TEXT),
                max_stock_level = CAST(max_stock_level AS TEXT)
        """)
        
        # Update StockMovement quantities using raw SQL
        cursor.execute("""
            UPDATE products_stockmovement 
            SET quantity = CAST(quantity AS TEXT)
        """)


def reverse_convert_decimal_to_integer(apps, schema_editor):
    """Reverse conversion - convert decimal back to integer using raw SQL"""
    db_alias = schema_editor.connection.alias
    
    # Update Product quantities back to integers using raw SQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE products_product 
            SET stock_quantity = CAST(stock_quantity AS INTEGER),
                min_stock_level = CAST(min_stock_level AS INTEGER),
                max_stock_level = CAST(max_stock_level AS INTEGER)
        """)
        
        # Update StockMovement quantities back to integers using raw SQL
        cursor.execute("""
            UPDATE products_stockmovement 
            SET quantity = CAST(quantity AS INTEGER)
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_max_stock_level_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_integer_to_decimal, reverse_convert_decimal_to_integer),
    ]
